### ISSUE TITLE
Release as library package

### ISSUE THREAD

**Issue by lpil** [jhrcek/force-layout#1]
Hello!

I'd love to use this algorithm in a an application of mine. Could this be released as a library?

Cheers,
Louis

**Comment by jhrcek** [comment]
Hello @lpil,
recently gampleman released much higher quality force directed layout algorithm implementation in his elm-visualization. I recommend you checking that out http://package.elm-lang.org/packages/gampleman/elm-visualization/1.3.0/Visualization-Force

**Comment by lpil** [comment]
Great! Thank you
